---
- name: Haproxy | Cleanup potentially deployed nginx-proxy
  become: true
  file:
    path: "{{ kube_manifest_dir }}/nginx-proxy.yml"
    state: absent

- name: Haproxy | Make haproxy directory
  become: true
  file:
    path: "{{ haproxy_config_dir }}"
    state: directory
    mode: 0755
    owner: root

- name: Haproxy | Write haproxy configuration
  become: true
  template:
    src: "loadbalancer/haproxy.cfg.j2"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
    owner: root
    mode: 0755
    backup: yes

- name: Haproxy | Get checksum from config
  become: true
  stat:
    path: "{{ haproxy_config_dir }}/haproxy.cfg"
    get_attributes: no
    get_checksum: yes
    get_mime: no
  register: haproxy_stat

- name: Haproxy | Write static pod
  become: true
  template:
    src: manifests/haproxy.manifest.j2
    dest: "{{ kube_manifest_dir }}/haproxy.yml"
    mode: 0640
