
- name: Install | Copy kubeadm binary from download dir
  become: true
  copy:
    src: "{{ downloads.kubeadm.dest }}"
    dest: "{{ bin_dir }}/kubeadm"
    mode: 0755
    remote_src: true
  tags:
    - kubeadm
#  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  when:
    - not inventory_hostname in groups['kube_control_plane']


- name: Install | Copy kubelet binary from download dir
  become: true
  copy:
    src: "{{ downloads.kubelet.dest }}"
    dest: "{{ bin_dir }}/kubelet"
    mode: 0755
    remote_src: true
  tags:
    - kubelet
    - upgrade
#  delegate_to: "{{ groups['kube_control_plane'][0] }}"
  notify: Node | restart kubelet
